# Generated by Django 5.1.6 on 2025-02-15 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HealthProfessional',
            fields=[
                ('id', models.AutoField(db_column='HealthProfessionalId', primary_key=True, serialize=False)),
                ('full_name', models.CharField(db_column='TrandingName', max_length=255)),
                ('social_name', models.CharField(blank=True, db_column='SocialName', max_length=255, null=True)),
                ('profession', models.CharField(db_column='Profession', max_length=100)),
                ('zipcode', models.CharField(db_column='ZipCode', max_length=10)),
                ('adress_street', models.TextField(db_column='AddressStreet', max_length=255)),
                ('adress_neighborhood', models.TextField(db_column='AddressNeighborhood', max_length=255)),
                ('city', models.CharField(db_column='City', max_length=100)),
                ('state', models.CharField(db_column='State', max_length=100)),
                ('phone', models.CharField(db_column='Phone', max_length=20)),
                ('email', models.EmailField(db_column='Email', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='CreationDate')),
                ('updated_at', models.DateTimeField(auto_now=True, db_column='UpdateDate')),
                ('deleted_at', models.DateTimeField(blank=True, db_column='DeletionDate', null=True)),
            ],
        ),
    ]
