# Generated by Django 5.1.6 on 2025-02-16 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('professionals', '0004_healthprofessional_adress_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='healthprofessional',
            name='taxnumber',
            field=models.CharField(db_column='TaxNumber', error_messages={'unique': 'Um usuário com esse CNPJ já existe.'}, max_length=20, unique=True),
        ),
    ]
