# Generated by Django 5.1.6 on 2025-02-16 17:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('professionals', '0005_alter_healthprofessional_taxnumber'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='healthprofessional',
            name='creation_user_id',
            field=models.ForeignKey(db_column='CreationUserId', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='health_professionals_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='healthprofessional',
            name='update_user_id',
            field=models.ForeignKey(db_column='UpdateUserId', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='health_professionals_updated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='profession',
            name='creation_user_id',
            field=models.ForeignKey(db_column='CreationUserId', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='professions_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='profession',
            name='update_user_id',
            field=models.ForeignKey(db_column='UpdateUserId', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='professions_updated', to=settings.AUTH_USER_MODEL),
        ),
    ]
