# Generated by Django 5.1.6 on 2025-02-15 17:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('professionals', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profession',
            fields=[
                ('id', models.AutoField(db_column='ProfessionId', primary_key=True, serialize=False)),
                ('name', models.CharField(db_column='Name', max_length=100)),
                ('description', models.TextField(db_column='Description', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='CreationDate')),
                ('updated_at', models.DateTimeField(auto_now=True, db_column='UpdateDate')),
                ('deleted_at', models.DateTimeField(blank=True, db_column='DeletionDate', null=True)),
            ],
            options={
                'db_table': 'Profession',
            },
        ),
        migrations.AlterModelTable(
            name='healthprofessional',
            table='HealthProfessional',
        ),
        migrations.AlterField(
            model_name='healthprofessional',
            name='profession',
            field=models.ForeignKey(db_column='ProfessionId', on_delete=django.db.models.deletion.DO_NOTHING, to='professionals.profession'),
        ),
    ]
