# Generated by Django 5.1.6 on 2025-03-02 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('professionals', '0006_healthprofessional_creation_user_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='healthprofessional',
            name='taxnumber',
            field=models.CharField(db_column='TaxNumber', error_messages={'unique': 'Um profissional com esse CPF já existe.'}, max_length=20, unique=True),
        ),
    ]
