# Generated by Django 5.1.6 on 2025-02-17 22:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('professionals', '0006_healthprofessional_creation_user_id_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.AutoField(db_column='AppointmentId', primary_key=True, serialize=False)),
                ('patient_name', models.CharField(db_column='PatientName', max_length=255)),
                ('patient_phone', models.CharField(db_column='PatientPhone', max_length=20)),
                ('patient_email', models.EmailField(db_column='PatientEmail', max_length=100)),
                ('appointment_date', models.DateField(db_column='AppointmentDate')),
                ('appointment_time', models.TimeField(db_column='AppointmentTime')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='CreationDate')),
                ('updated_at', models.DateTimeField(auto_now=True, db_column='UpdateDate')),
                ('deleted_at', models.DateTimeField(blank=True, db_column='DeletionDate', null=True)),
                ('creation_user_id', models.ForeignKey(db_column='CreationUserId', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='appointments_created', to=settings.AUTH_USER_MODEL)),
                ('health_professional', models.ForeignKey(db_column='HealthProfessionalId', on_delete=django.db.models.deletion.CASCADE, to='professionals.healthprofessional')),
                ('update_user_id', models.ForeignKey(db_column='UpdateUserId', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='appointments_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'Appointment',
            },
        ),
    ]
