# Generated by Django 5.1.6 on 2025-02-18 23:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0001_initial'),
        ('professionals', '0006_healthprofessional_creation_user_id_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='appointment',
            unique_together={('appointment_date', 'appointment_time', 'health_professional')},
        ),
    ]
